apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  # add the number of replicats you want 
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
      # add docker registry image 
        image: dockertokubernetesregistry.azurecr.io/movietheaterangularimage
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
    
# create a service that will allow to access the application 
# type service and press enter

---

  apiVersion: v1
  kind: Service
  metadata:
    name: myapp
  spec:
    type: NodePort
    selector:
      app: myapp
    ports:
    - port: 80
      targetPort: 8080
  